version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:3000'
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=123qwe123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vegalicious
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
