version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: posgrespassword
      POSTGRES_DB: vegalicious
    ports:
      - 5432:5432
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: posgrespassword
      POSTGRES_DB: vegalicious
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
